targets:
  $default:
    sources:
      - lib/**
      - test/**
    builders:
      entity_sync_generator|use_entity_sync_builder:
        enabled: false
      drift_dev|not_shared:
        enabled: false
      mockito|mockBuilder:
        enabled: false
