name: entity_sync
version: 0.1.0
description: An entity sync library for Dart developers.
homepage: https://github.com/qBozo/entity_sync

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^0.13.6
  drift: ^2.10.0
  meta: ^1.9.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.4.2
  drift_dev: ^2.10.0
